# Generated by Django 4.0 on 2022-09-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
