# Generated by Django 4.0 on 2022-09-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_developer_role_alter_project_project_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='role',
            field=models.CharField(choices=[('Dev-ops', 'Dev-ops'), ('Full-stack', 'Full-stack'), ('Back-end', 'Back-end'), ('Front-end', 'Front-end')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_role',
            field=models.CharField(blank=True, choices=[('Dev-ops', 'Dev-ops'), ('Full-stack', 'Full-stack'), ('Back-end', 'Back-end'), ('Front-end', 'Front-end')], max_length=100, null=True),
        ),
    ]
